spring.application.name=Booksy
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}


cloudflare.r2.endpoint=https://c1c10e22ccb359d0a16e38bc9210eff4.r2.cloudflarestorage.com
cloudflare.r2.bucket=booksy-images
cloudflare.r2.public-url=https://pub-e11e85b560ca4ebd984ab68950269324.r2.dev
cloudflare.r2.access-key=${R2_ACCESS_KEY}
cloudflare.r2.secret-key=${R2_SECRET_KEY}


logging.level.org.springframework.security=DEBUG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=booksy-super-secret-key-team16-2026-very-long-string
